#ifndef DEFINES_H_
#define DEFINES_H_
#include "Vector.h"

#define VIKING_NAME "Viking"
#define BATTLE_CRUSER_NAME "BattleCruser"
#define PHOENIX_NAME "Phoenix"
#define CARRIER_NAME "Carrier"

int errNo;
int internErrNo;

enum AirShipDefines {
  BATTLE_CRUSER_HEALTH = 450,
  BATTLE_BRUSER_DAMAGE = 40,

  VIKING_HEALTH = 150,
  VIKING_DAMAGE = 15,

  CARRIER_HEALTH = 200,
  CARRIER_SHIELD = 150,
  CARRIER_DAMAGE = 8,
  CARRIER_SHIELD_REGENERATE_RATE = 40,

  PHOENIX_HEALTH = 90,
  PHOENIX_SHIELD = 90,
  PHOENIX_DAMAGE = 20,
  PHOENIX_SHIELD_REGENERATE_RATE = 20,
  MAX_AIRSHIP_NAME_SIZE = 20
};

enum AirShipType {
  BATTLE_CRUSER, VIKING, CARRIER, PHOENIX
};

enum CarrierDefines {
  MAX_INTERCEPTORS = 8,
  DAMAGED_STATUS_INTERCEPTORS = 4
};

enum BattleCruserDefines {
  YAMATO_CANNON_LOADING_TURNS = 5,
  BATTLE_BRUSER_POWER_DAMAGE = 200
};

enum VikingDefines{
  VIKING_DOUBLE_DAMAGE = 30
};
enum PhoenixDefines{
  PHOENIX_ATTACKS = 1
};

#endif /* DEFINES_H_ */